export const MOCK_DOCTORS = [
  {
    IdDoctor: 1,
    Nombre: "Dra. Valentina Herrera Soto",
    Especialidad: "Radiología Diagnóstica",
    Cedula: "MX-RAD-2018-04821",
    Email: "v.herrera@detectit.mx",
    Telefono: "+52 664 210 3847",
    Ubicacion: "Tijuana, Baja California",
    Hospital: "Hospital Ángeles Tijuana",
    Experiencia: "9 años",
    Bio: "Especialista en radiodiagnóstico con enfoque en detección temprana de enfermedades pulmonares y musculoesqueléticas. Formada en el IMSS con subespecialidad en imagen de tórax.",
    FechaCreacion: "2024-01-15T08:00:00.000Z",
    FechaActualizacion: "2026-04-01T10:30:00.000Z",
    education: [
      { IdEducacion: 1, Titulo: "Especialidad en Radiología", Escuela: "IMSS CDMX", Anio: "2018" },
      { IdEducacion: 2, Titulo: "Médico Cirujano", Escuela: "UABC Tijuana", Anio: "2014" },
    ],
    certifications: [
      { IdCertificacion: 1, Nombre: "FMRI" },
      { IdCertificacion: 2, Nombre: "ACR Member" },
      { IdCertificacion: 3, Nombre: "RSNA 2023" },
    ],
    activity: [
      { IdActividad: 1, Paciente: "Rodrigo Fuentes, 47", Estudio: "Rx Tórax PA",     Tiempo: "Hace 15 min", Estado: "Completado" },
      { IdActividad: 2, Paciente: "Sofía Delgado, 33",   Estudio: "Rx Columna L-S", Tiempo: "Hace 1h",     Estado: "En revisión" },
      { IdActividad: 3, Paciente: "Ernesto Vega, 58",    Estudio: "Rx Mano Izq.",   Tiempo: "Hace 2h",     Estado: "Completado" },
      { IdActividad: 4, Paciente: "Mariana Castro, 26",  Estudio: "Rx Tórax PA",    Tiempo: "Ayer",        Estado: "Completado" },
    ],
  },
  {
    IdDoctor: 2,
    Nombre: "Dr. Alejandro Montoya Cruz",
    Especialidad: "Radiología Intervencionista",
    Cedula: "MX-RAD-2015-03312",
    Email: "a.montoya@detectit.mx",
    Telefono: "+52 664 388 9210",
    Ubicacion: "Tijuana, Baja California",
    Hospital: "Centro Médico del Noroeste",
    Experiencia: "12 años",
    Bio: "Radiólogo intervencionista especializado en biopsias guiadas por imagen y tratamiento de tumores mediante radiofrecuencia.",
    FechaCreacion: "2024-01-15T08:00:00.000Z",
    FechaActualizacion: "2026-03-28T09:15:00.000Z",
    education: [
      { IdEducacion: 3, Titulo: "Subespecialidad en Radiología Intervencionista", Escuela: "Hospital General de México", Anio: "2015" },
      { IdEducacion: 4, Titulo: "Especialidad en Radiología", Escuela: "UNAM CDMX", Anio: "2012" },
      { IdEducacion: 5, Titulo: "Médico Cirujano", Escuela: "Universidad de Guadalajara", Anio: "2008" },
    ],
    certifications: [
      { IdCertificacion: 4, Nombre: "SIR Member" },
      { IdCertificacion: 5, Nombre: "CIRSE 2022" },
    ],
    activity: [
      { IdActividad: 5, Paciente: "Patricia Leal, 62",  Estudio: "Biopsia guiada",   Tiempo: "Hace 30 min", Estado: "Completado" },
      { IdActividad: 6, Paciente: "Héctor Ríos, 55",    Estudio: "Rx Abdomen",       Tiempo: "Hace 3h",     Estado: "Completado" },
    ],
  },
]

export const MOCK_PATIENTS = [
  {
    IdPaciente: 1,
    Nombre: "Rodrigo Fuentes Alvarado",
    Edad: 47,
    Sexo: "Masculino",
    FechaNacimiento: "1978-09-14",
    TipoSangre: "A+",
    Email: "r.fuentes@gmail.com",
    Telefono: "+52 664 501 7823",
    Ubicacion: "Tijuana, Baja California",
    Seguro: "IMSS — Afiliado #391-04-8821",
    ContactoEmergencia: "Laura Fuentes · +52 664 302 4410",
    IdDoctor: 1,
    NombreDoctor: "Dra. Valentina Herrera Soto",
    FechaCreacion: "2022-03-10T10:00:00.000Z",
    FechaActualizacion: "2026-04-15T14:20:00.000Z",
    allergies:   [{ IdAlergia: 1, Nombre: "Penicilina" }, { IdAlergia: 2, Nombre: "Ibuprofeno" }],
    medications: [
      { IdMedicamento: 1, Nombre: "Enalapril 10mg",    Frecuencia: "1 vez al día",   Desde: "2021" },
      { IdMedicamento: 2, Nombre: "Atorvastatina 20mg",Frecuencia: "1 vez al día",   Desde: "2022" },
    ],
    conditions:  [{ IdCondicion: 1, Nombre: "Hipertensión arterial" }, { IdCondicion: 2, Nombre: "Dislipidemia" }],
    vitals: { PresionArterial: "142/90 mmHg", FrecuenciaCardiaca: "78 bpm", Temperatura: "36.6 °C", Peso: "88 kg", Talla: "1.75 m", IMC: "28.7" },
    studies: [
      { IdEstudio: 1, Tipo: "Rx Tórax PA",    Fecha: "15/04/2026", Doctor: "Dra. Herrera", Resultado: "Normal",            Estado: "Completado" },
      { IdEstudio: 2, Tipo: "Rx Columna L-S", Fecha: "20/01/2026", Doctor: "Dra. Herrera", Resultado: "Osteofitos leves",  Estado: "Completado" },
    ],
  },
  {
    IdPaciente: 2,
    Nombre: "Sofía Delgado Paredes",
    Edad: 33,
    Sexo: "Femenino",
    FechaNacimiento: "1992-05-22",
    TipoSangre: "O-",
    Email: "sofia.delgado@hotmail.com",
    Telefono: "+52 664 722 3391",
    Ubicacion: "Ensenada, Baja California",
    Seguro: "Seguro Popular",
    ContactoEmergencia: "Miguel Delgado · +52 664 810 5567",
    IdDoctor: 1,
    NombreDoctor: "Dra. Valentina Herrera Soto",
    FechaCreacion: "2023-07-05T09:30:00.000Z",
    FechaActualizacion: "2026-03-30T11:45:00.000Z",
    allergies:   [{ IdAlergia: 3, Nombre: "Sulfonamidas" }],
    medications: [
      { IdMedicamento: 3, Nombre: "Levotiroxina 50mcg", Frecuencia: "1 vez al día en ayuno", Desde: "2023" },
    ],
    conditions:  [{ IdCondicion: 3, Nombre: "Hipotiroidismo" }],
    vitals: { PresionArterial: "118/74 mmHg", FrecuenciaCardiaca: "68 bpm", Temperatura: "36.2 °C", Peso: "61 kg", Talla: "1.63 m", IMC: "22.9" },
    studies: [
      { IdEstudio: 3, Tipo: "Rx Columna L-S", Fecha: "30/03/2026", Doctor: "Dra. Herrera", Resultado: "Sin hallazgos", Estado: "Completado" },
    ],
  },
  {
    IdPaciente: 3,
    Nombre: "Ernesto Vega Cisneros",
    Edad: 58,
    Sexo: "Masculino",
    FechaNacimiento: "1967-11-03",
    TipoSangre: "B+",
    Email: "e.vega@yahoo.com.mx",
    Telefono: "+52 664 933 1204",
    Ubicacion: "Tijuana, Baja California",
    Seguro: "ISSSTE — Afiliado #770-22-1093",
    ContactoEmergencia: "Carmen Vega · +52 664 441 8832",
    IdDoctor: 1,
    NombreDoctor: "Dra. Valentina Herrera Soto",
    FechaCreacion: "2020-11-18T08:00:00.000Z",
    FechaActualizacion: "2026-04-10T16:00:00.000Z",
    allergies:   [],
    medications: [
      { IdMedicamento: 4, Nombre: "Metformina 850mg", Frecuencia: "2 veces al día", Desde: "2018" },
      { IdMedicamento: 5, Nombre: "Glibenclamida 5mg",Frecuencia: "1 vez al día",   Desde: "2020" },
      { IdMedicamento: 6, Nombre: "Lisinopril 20mg",  Frecuencia: "1 vez al día",   Desde: "2019" },
    ],
    conditions:  [{ IdCondicion: 4, Nombre: "Diabetes tipo 2" }, { IdCondicion: 5, Nombre: "Hipertensión arterial" }, { IdCondicion: 6, Nombre: "Retinopatía diabética leve" }],
    vitals: { PresionArterial: "150/95 mmHg", FrecuenciaCardiaca: "82 bpm", Temperatura: "36.8 °C", Peso: "95 kg", Talla: "1.70 m", IMC: "32.9" },
    studies: [
      { IdEstudio: 4, Tipo: "Rx Mano Izq.",  Fecha: "10/04/2026", Doctor: "Dra. Herrera", Resultado: "Artritis leve", Estado: "Completado" },
      { IdEstudio: 5, Tipo: "Rx Tórax PA",   Fecha: "15/09/2025", Doctor: "Dra. Herrera", Resultado: "Normal",        Estado: "Completado" },
    ],
  },
  {
    IdPaciente: 4,
    Nombre: "Mariana Castro Ibáñez",
    Edad: 26,
    Sexo: "Femenino",
    FechaNacimiento: "1999-02-17",
    TipoSangre: "AB+",
    Email: "mariana.castro99@gmail.com",
    Telefono: "+52 664 615 4490",
    Ubicacion: "Tecate, Baja California",
    Seguro: "IMSS — Afiliado #612-88-2347",
    ContactoEmergencia: "Jorge Castro · +52 664 700 1122",
    IdDoctor: 2,
    NombreDoctor: "Dr. Alejandro Montoya Cruz",
    FechaCreacion: "2025-01-20T11:00:00.000Z",
    FechaActualizacion: "2026-04-08T09:10:00.000Z",
    allergies:   [{ IdAlergia: 4, Nombre: "Aspirina" }, { IdAlergia: 5, Nombre: "Látex" }],
    medications: [],
    conditions:  [],
    vitals: { PresionArterial: "112/70 mmHg", FrecuenciaCardiaca: "64 bpm", Temperatura: "36.1 °C", Peso: "55 kg", Talla: "1.60 m", IMC: "21.5" },
    studies: [
      { IdEstudio: 6, Tipo: "Rx Tórax PA", Fecha: "08/04/2026", Doctor: "Dr. Montoya", Resultado: "Normal", Estado: "Completado" },
    ],
  },
  {
    IdPaciente: 5,
    Nombre: "Patricia Leal Garza",
    Edad: 62,
    Sexo: "Femenino",
    FechaNacimiento: "1963-08-29",
    TipoSangre: "A-",
    Email: "pleal@prodigy.net.mx",
    Telefono: "+52 664 334 8801",
    Ubicacion: "Mexicali, Baja California",
    Seguro: "IMSS — Afiliado #201-67-9910",
    ContactoEmergencia: "Roberto Leal · +52 664 512 3344",
    IdDoctor: 2,
    NombreDoctor: "Dr. Alejandro Montoya Cruz",
    FechaCreacion: "2021-06-01T07:30:00.000Z",
    FechaActualizacion: "2026-04-30T10:00:00.000Z",
    allergies:   [{ IdAlergia: 6, Nombre: "Contraste yodado" }],
    medications: [
      { IdMedicamento: 7, Nombre: "Omeprazol 20mg",   Frecuencia: "1 vez al día",   Desde: "2021" },
      { IdMedicamento: 8, Nombre: "Calcio + Vit D",   Frecuencia: "1 vez al día",   Desde: "2022" },
    ],
    conditions:  [{ IdCondicion: 7, Nombre: "Osteoporosis" }, { IdCondicion: 8, Nombre: "Reflujo gastroesofágico" }],
    vitals: { PresionArterial: "125/80 mmHg", FrecuenciaCardiaca: "72 bpm", Temperatura: "36.4 °C", Peso: "67 kg", Talla: "1.58 m", IMC: "26.8" },
    studies: [
      { IdEstudio: 7, Tipo: "Biopsia guiada", Fecha: "30/04/2026", Doctor: "Dr. Montoya", Resultado: "Pendiente",  Estado: "En revisión" },
      { IdEstudio: 8, Tipo: "Rx Cadera Izq.", Fecha: "12/01/2026", Doctor: "Dr. Montoya", Resultado: "Osteopenia", Estado: "Completado" },
    ],
  },
]

export const MOCK_RECORDS: Record<number, { patient: (typeof MOCK_PATIENTS)[0]; entries: object[] }> = {
  1: {
    patient: MOCK_PATIENTS[0],
    entries: [
      {
        IdEntrada: 1, Fecha: "15/04/2026", Tipo: "Estudio radiológico",
        Doctor: "Dra. Valentina Herrera Soto", Titulo: "Rx Tórax PA — Control",
        Resumen: "Campos pulmonares sin condensaciones. Silueta cardíaca en límites normales.",
        Hallazgos: "Sin infiltrados ni masas. Costillas simétricas. Tráquea centrada.",
        Diagnostico: "Rx de tórax dentro de parámetros normales.",
        Recomendaciones: "Continuar control de hipertensión. Seguimiento anual.",
        TieneImagen: true,
        NotaIA: "IA detectó índice cardiotorácico: 0.47 (normal). Sin opacidades de patología aguda.",
        FechaCreacion: "2026-04-15T10:00:00.000Z",
      },
      {
        IdEntrada: 2, Fecha: "20/01/2026", Tipo: "Estudio radiológico",
        Doctor: "Dra. Valentina Herrera Soto", Titulo: "Rx Columna Lumbosacra",
        Resumen: "Leve disminución de espacios intervertebrales en L5-S1. Osteofitos marginales.",
        Hallazgos: "Pérdida discreta de altura discal L5-S1. Lordosis conservada.",
        Diagnostico: "Espondiloartrosis lumbar leve.",
        Recomendaciones: "Ejercicios de fortalecimiento lumbar. Evitar sobrepeso.",
        TieneImagen: true,
        NotaIA: "IA identificó reducción discal L5-S1 con probabilidad 81%.",
        FechaCreacion: "2026-01-20T09:30:00.000Z",
      },
      {
        IdEntrada: 3, Fecha: "05/09/2025", Tipo: "Consulta",
        Doctor: "Dra. Valentina Herrera Soto", Titulo: "Consulta de control — Hipertensión",
        Resumen: "TA: 142/90. Paciente refiere buena adherencia. Ajuste de dosis de Enalapril.",
        Hallazgos: "Sin edema periférico. Pulsos presentes y simétricos.",
        Diagnostico: "Hipertensión arterial con control subóptimo.",
        Recomendaciones: "Aumentar Enalapril a 10mg. Dieta hiposódica. Actividad física.",
        TieneImagen: false, NotaIA: null,
        FechaCreacion: "2025-09-05T11:00:00.000Z",
      },
    ],
  },
  2: {
    patient: MOCK_PATIENTS[1],
    entries: [
      {
        IdEntrada: 4, Fecha: "30/03/2026", Tipo: "Estudio radiológico",
        Doctor: "Dra. Valentina Herrera Soto", Titulo: "Rx Columna L-S — Primera vez",
        Resumen: "Sin alteraciones estructurales. Alineación vertebral conservada.",
        Hallazgos: "Espacios discales normales. Sin listesis ni escoliosis.",
        Diagnostico: "Columna lumbosacra sin hallazgos patológicos.",
        Recomendaciones: "Sin indicación de estudios complementarios.",
        TieneImagen: true,
        NotaIA: "IA: Sin hallazgos anormales con 96% de confianza.",
        FechaCreacion: "2026-03-30T14:00:00.000Z",
      },
    ],
  },
}
